<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\WebServerBundle\WebServerBundle::class => ['dev' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Knp\Bundle\MenuBundle\KnpMenuBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    FOS\UserBundle\FOSUserBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Disjfa\GlynnTemplateBundle\GlynnTemplateBundle::class => ['all' => true],
    Ornicar\GravatarBundle\OrnicarGravatarBundle::class => ['all' => true],
    Translation\Bundle\TranslationBundle::class => ['all' => true],
    Disjfa\TimetableBundle\DisjfaTimetableBundle::class => ['all' => true],
    SamJ\FractalBundle\SamJFractalBundle::class => ['all' => true],
    Knp\Bundle\PaginatorBundle\KnpPaginatorBundle::class => ['all' => true],
    PhpMob\SettingsBundle\PhpMobSettingsBundle::class => ['all' => true],
    Enqueue\Bundle\EnqueueBundle::class => ['all' => true],
    Disjfa\EnqueueBundle\DisjfaEnqueueBundle::class => ['all' => true],
    Disjfa\MozaicBundle\DisjfaMozaicBundle::class => ['all' => true],
    Disjfa\TranslationBundle\DisjfaTranslationBundle::class => ['all' => true],
    Disjfa\MediaBundle\DisjfaMediaBundle::class => ['all' => true],
    Disjfa\MenuBundle\DisjfaMenuBundle::class => ['all' => true],
    Disjfa\MapsBundle\DisjfaMapsBundle::class => ['all' => true],
    Liip\ImagineBundle\LiipImagineBundle::class => ['all' => true],
    Disjfa\PwaBundle\DisjfaPwaBundle::class => ['all' => true],
    Toiba\FullCalendarBundle\FullCalendarBundle::class => ['all' => true],
    Disjfa\EventBundle\DisjfaEventBundle::class => ['all' => true],
    EasyCorp\Bundle\EasyAdminBundle\EasyAdminBundle::class => ['all' => true],
    Symfony\WebpackEncoreBundle\WebpackEncoreBundle::class => ['all' => true],
    Twig\Inky\Bundle\TwigInkyBundle::class => ['all' => true],
    Twig\CssInliner\Bundle\TwigCssInlinerBundle::class => ['all' => true],
];
